// 이 파일은 자동 생성 파일입니다. (직접 수정 금지)
export const iconNames = [
  'chippi_profile',
  'dotori',
  'ext_home1',
  'ext_home2',
  'extension_pop',
  'extension_thumb',
  'google',
  'ic_arrow_down_active',
  'ic_arrow_down_disable',
  'ic_bookmark_active',
  'ic_bookmark_disable',
  'ic_clock_active',
  'ic_clock_disable',
  'ic_close',
  'ic_details_category',
  'ic_details_disable',
  'ic_extension',
  'ic_info',
  'ic_plus',
  'instagram',
  'logo',
  'logout_chippi.2512',
  'main_header_logo',
  'main_logo',
  'palms',
  'saved',
  'tooltip_1',
  'tooltip_2',
  'tooltip_3',
  'tooltip_4',
  'tooltip_5',
] as const;
export type IconName = (typeof iconNames)[number];
