// 이 파일은 자동 생성 파일입니다. (직접 수정 금지)
export const iconNames = [
  'check_circle',
  'ext_home1',
  'ext_home2',
  'google',
  'ic_arrow_down_active',
  'ic_arrow_down_disable',
  'ic_bookmark_active',
  'ic_bookmark_disable',
  'ic_clock_active',
  'ic_clock_disable',
  'ic_close',
  'ic_details_category',
  'ic_details_disable',
  'ic_extension',
  'ic_info',
  'ic_memo',
  'ic_pin',
  'ic_pin_active',
  'ic_pin_disable',
  'ic_plus',
  'instagram',
  'logo',
  'main_header_logo',
  'main_logo',
  'notsave_circle',
] as const;
export type IconName = (typeof iconNames)[number];
