export const REMIND_MOCK_DATA = [
  {
    id: 1,
    title: '리액트 쿼리 강의 듣기',
    content: '1강부터 5강까지 완강하고 복습하기',
    timeRemaining: '1시간 30분',
    category: '공부',
  },
  {
    id: 2,
    title: '장보기',
    content: '우유, 계란, 채소 구매',
    timeRemaining: '3시간 00분',
    category: '생활',
  },
  {
    id: 3,
    title: '프로젝트 기획서 초안 작성',
    content: '주요 기능 및 화면 흐름 정리',
    timeRemaining: '완료',
    category: '업무',
  },
  {
    id: 4,
    title: '헬스장 가기',
    content: '하체 운동 루틴 진행',
    timeRemaining: '5시간 10분',
    category: '운동',
  },
  {
    id: 5,
    title: '주간 회고 작성',
    content: '이번 주에 배운 점과 개선할 점 정리',
    timeRemaining: '완료',
    category: '자기계발',
  },
  {
    id: 6,
    title: '저녁 약속',
    content: '강남역 2번 출구에서 친구 만나기',
    timeRemaining: '8시간 00분',
    category: '약속',
  },
  {
    id: 7,
    title: '알고리즘 문제 풀기',
    content: '백준 골드 문제 2개 풀기',
    timeRemaining: '2시간 45분',
    category: '공부',
  },
  {
    id: 8,
    title: '이메일 회신',
    content: 'A사에서 온 제휴 문의 메일 확인하고 회신',
    timeRemaining: '완료',
    category: '업무',
  },
  {
    id: 9,
    title: '방 청소하기',
    content: '책상 정리 및 바닥 청소기 돌리기',
    timeRemaining: '0시간 50분',
    category: '생활',
  },
  {
    id: 10,
    title: 'TypeScript 스터디 준비',
    content: '제네릭 파트 발표 자료 만들기',
    timeRemaining: '10시간 00분',
    category: '공부',
  },
  {
    id: 11,
    title: '은행 업무 보기',
    content: '만기 된 예금 재예치하기',
    timeRemaining: '완료',
    category: '금융',
  },
  {
    id: 12,
    title: '블로그 글 작성',
    content: '이번 주에 해결한 기술적 문제에 대해 포스팅하기',
    timeRemaining: '1일 2시간',
    category: '자기계발',
  },
  {
    id: 13,
    title: '가족과 통화하기',
    content: '부모님께 안부 전화드리기',
    timeRemaining: '4시간 20분',
    category: '약속',
  },
  {
    id: 14,
    title: '주말 산책 계획',
    content: '가까운 공원 산책 코스 찾아보기',
    timeRemaining: '2일 0시간',
    category: '여가',
  },
  {
    id: 15,
    title: '팀 회의록 정리',
    content: '어제 진행된 스프린트 계획 회의 내용 정리해서 공유',
    timeRemaining: '완료',
    category: '업무',
  },
  {
    id: 16,
    title: '팀 회의록 정리',
    content: '어제 진행된 스프린트 계획 회의 내용 정리해서 공유',
    timeRemaining: '완료',
    category: '업무',
  },
];
