/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull prod'
 *
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 1
 * Build: 1.0.0
 * Runtime: browser:typescript-ampli-v2
 *
 * [View Tracking Plan](https://data.amplitude.com/pinback/default/events/main/latest)
 *
 * [Full Setup Instructions](https://data.amplitude.com/pinback/default/implementation/prod)
 */

import * as amplitude from '@amplitude/analytics-browser';

export type Environment = 'default';

export const ApiKey: Record<Environment, string> = {
  default: 'bb48a29e445e2f350a1d23ad67f38d55'
};

/**
 * Default Amplitude configuration options. Contains tracking plan information.
 */
export const DefaultConfiguration: BrowserOptions = {
  plan: {
    version: '1',
    branch: 'main',
    source: 'prod',
    versionId: 'a8d7f423-b996-4b7f-b836-cd64e2319f47'
  },
  ...{
    ingestionMetadata: {
      sourceName: 'browser-typescript-ampli',
      sourceVersion: '2.0.0'
    }
  }
};

export interface LoadOptionsBase { disabled?: boolean }

export type LoadOptionsWithEnvironment = LoadOptionsBase & { environment: Environment; client?: { configuration?: BrowserOptions; }; };
export type LoadOptionsWithApiKey = LoadOptionsBase & { client: { apiKey: string; configuration?: BrowserOptions; } };
export type LoadOptionsWithClientInstance = LoadOptionsBase & { client: { instance: BrowserClient; } };

export type LoadOptions = LoadOptionsWithEnvironment | LoadOptionsWithApiKey | LoadOptionsWithClientInstance;

export interface IdentifyProperties {
  job_role?: string;
}

export interface ClickedAlarmProperties {
  /**
   * 아티클 고유 ID (특정 아티클 재열람 확인 등)
   */
  article_id?: string;
  /**
   * 리마인드 아이디(보내고 클릭해졌는지 클릭률 계산 등)
   */
  reminder_id?: string;
}

export interface ClickedMyBookmarkProperties {
  /**
   * 아티클 고유 ID (특정 아티클 재열람 확인 등)
   */
  article_id?: string;
  /**
   * 카테고리 고유 ID (어디에 저장됐는지, 공유 여부 확인 등)
   */
  category_id?: string;
}

export interface ClickedReminderProperties {
  /**
   * 아티클 고유 ID (특정 아티클 재열람 확인 등)
   */
  article_id?: string;
  /**
   * 리마인드 아이디(보내고 클릭해졌는지 클릭률 계산 등)
   */
  reminder_id?: string;
}

export interface ClickedSharedBookmarkProperties {
  /**
   * 아티클 고유 ID (특정 아티클 재열람 확인 등)
   */
  article_id?: string;
  /**
   * 카테고리 고유 ID (어디에 저장됐는지, 공유 여부 확인 등)
   */
  category_id?: string;
}

export interface ImpressionSavedContentProperties {
  /**
   * 아티클 고유 ID (특정 아티클 재열람 확인 등)
   */
  article_id?: string;
  /**
   * 콘텐츠 유입 출처
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | own, jobpin, remind |
   */
  bookmark_type?: "own" | "jobpin" | "remind";
  /**
   * 카테고리 고유 ID (어디에 저장됐는지, 공유 여부 확인 등)
   */
  category_id?: string;
}

export interface SavedArticleProperties {
  /**
   * 아티클 고유 ID (특정 아티클 재열람 확인 등)
   */
  article_id?: string;
  /**
   * 카테고리 고유 ID (어디에 저장됐는지, 공유 여부 확인 등)
   */
  category_id?: string;
  /**
   * 첫 저장인지 여부
   */
  is_first_save?: boolean;
  /**
   * 저장 대상 페이지 도메인
   */
  page_domain?: string;
}

export interface SavedSharedBookmarkProperties {
  /**
   * 아티클 고유 ID (특정 아티클 재열람 확인 등)
   */
  article_id?: string;
  /**
   * 콘텐츠 유입 출처
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | own, jobpin, remind |
   */
  bookmark_type?: "own" | "jobpin" | "remind";
  /**
   * 카테고리 고유 ID (어디에 저장됐는지, 공유 여부 확인 등)
   */
  category_id?: string;
}

export interface TriggeredReminderProperties {
  /**
   * 아티클 고유 ID (특정 아티클 재열람 확인 등)
   */
  article_id?: string;
  /**
   * 카테고리 고유 ID (어디에 저장됐는지, 공유 여부 확인 등)
   */
  category_id?: string;
}

export class Identify implements BaseEvent {
  event_type = amplitude.Types.SpecialEventType.IDENTIFY;

  constructor(
    public event_properties?: IdentifyProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class ClickedAlarm implements BaseEvent {
  event_type = 'Clicked_alarm';

  constructor(
    public event_properties?: ClickedAlarmProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class ClickedMyBookmark implements BaseEvent {
  event_type = 'Clicked_My_Bookmark';

  constructor(
    public event_properties?: ClickedMyBookmarkProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class ClickedReminder implements BaseEvent {
  event_type = 'Clicked_Reminder';

  constructor(
    public event_properties?: ClickedReminderProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class ClickedSharedBookmark implements BaseEvent {
  event_type = 'Clicked_Shared_Bookmark';

  constructor(
    public event_properties?: ClickedSharedBookmarkProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class ImpressionSavedContent implements BaseEvent {
  event_type = 'Impression_Saved_Content';

  constructor(
    public event_properties?: ImpressionSavedContentProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class SavedArticle implements BaseEvent {
  event_type = 'Saved_Article';

  constructor(
    public event_properties?: SavedArticleProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class SavedSharedBookmark implements BaseEvent {
  event_type = 'Saved_Shared_Bookmark';

  constructor(
    public event_properties?: SavedSharedBookmarkProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class TriggeredReminder implements BaseEvent {
  event_type = 'Triggered_Reminder';

  constructor(
    public event_properties?: TriggeredReminderProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export type PromiseResult<T> = { promise: Promise<T | void> };

const getVoidPromiseResult = () => ({ promise: Promise.resolve() });

// prettier-ignore
export class Ampli {
  private disabled: boolean = false;
  private amplitude?: BrowserClient;

  get client(): BrowserClient {
    this.isInitializedAndEnabled();
    return this.amplitude!;
  }

  get isLoaded(): boolean {
    return this.amplitude != null;
  }

  private isInitializedAndEnabled(): boolean {
    if (!this.amplitude) {
      console.error('ERROR: Ampli is not yet initialized. Have you called ampli.load() on app start?');
      return false;
    }
    return !this.disabled;
  }

  /**
   * Initialize the Ampli SDK. Call once when your application starts.
   *
   * @param options Configuration options to initialize the Ampli SDK with.
   */
  load(options: LoadOptions): PromiseResult<void> {
    this.disabled = options.disabled ?? false;

    if (this.amplitude) {
      console.warn('WARNING: Ampli is already intialized. Ampli.load() should be called once at application startup.');
      return getVoidPromiseResult();
    }

    let apiKey: string | null = null;
    if (options.client && 'apiKey' in options.client) {
      apiKey = options.client.apiKey;
    } else if ('environment' in options) {
      apiKey = ApiKey[options.environment];
    }

    if (options.client && 'instance' in options.client) {
      this.amplitude = options.client.instance;
    } else if (apiKey) {
      this.amplitude = amplitude.createInstance();
      const configuration = (options.client && 'configuration' in options.client) ? options.client.configuration : {};
      return this.amplitude.init(apiKey, undefined, { ...DefaultConfiguration, ...configuration });
    } else {
      console.error("ERROR: ampli.load() requires 'environment', 'client.apiKey', or 'client.instance'");
    }

    return getVoidPromiseResult();
  }

  /**
   * Identify a user and set user properties.
   *
   * @param userId The user's id.
   * @param properties The user properties.
   * @param options Optional event options.
   */
  identify(
    userId: string | undefined,
    properties?: IdentifyProperties,
    options?: EventOptions,
  ): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    if (userId) {
      options = {...options,  user_id: userId};
    }

    const amplitudeIdentify = new amplitude.Identify();
    const eventProperties = properties;
    if (eventProperties != null) {
      for (const [key, value] of Object.entries(eventProperties)) {
        amplitudeIdentify.set(key, value);
      }
    }
    return this.amplitude!.identify(
      amplitudeIdentify,
      options,
    );
  }

 /**
  * Flush the event.
  */
  flush() : PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.flush();
  }

  /**
   * Track event
   *
   * @param event The event to track.
   * @param options Optional event options.
   */
  track(event: Event, options?: EventOptions): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.track(event, undefined, options);
  }

  /**
   * Clicked_alarm
   *
   * [View in Tracking Plan](https://data.amplitude.com/pinback/default/events/main/latest/Clicked_alarm)
   *
   * 알림을 클릭했을 때 발생
   *
   * @param properties The event's properties (e.g. article_id)
   * @param options Amplitude event options.
   */
  clickedAlarm(
    properties?: ClickedAlarmProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickedAlarm(properties), options);
  }

  /**
   * Clicked_My_Bookmark
   *
   * [View in Tracking Plan](https://data.amplitude.com/pinback/default/events/main/latest/Clicked_My_Bookmark)
   *
   * 대시보드 나의 북마크 카드를 클릭했을 때 발생 (여기서 나의 북마크는 북마크 전체, 카테고리 등 전체를 포함함.)
   *
   * @param properties The event's properties (e.g. article_id)
   * @param options Amplitude event options.
   */
  clickedMyBookmark(
    properties?: ClickedMyBookmarkProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickedMyBookmark(properties), options);
  }

  /**
   * Clicked_Reminder
   *
   * [View in Tracking Plan](https://data.amplitude.com/pinback/default/events/main/latest/Clicked_Reminder)
   *
   * 대시보드 리마인드 카드를 클릭했을 때 발생
   *
   * @param properties The event's properties (e.g. article_id)
   * @param options Amplitude event options.
   */
  clickedReminder(
    properties?: ClickedReminderProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickedReminder(properties), options);
  }

  /**
   * Clicked_Shared_Bookmark
   *
   * [View in Tracking Plan](https://data.amplitude.com/pinback/default/events/main/latest/Clicked_Shared_Bookmark)
   *
   * 공유 북마크 카드를 클릭했을 때 발생
   *
   * @param properties The event's properties (e.g. article_id)
   * @param options Amplitude event options.
   */
  clickedSharedBookmark(
    properties?: ClickedSharedBookmarkProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickedSharedBookmark(properties), options);
  }

  /**
   * Impression_Saved_Content
   *
   * [View in Tracking Plan](https://data.amplitude.com/pinback/default/events/main/latest/Impression_Saved_Content)
   *
   * 저장한 콘텐츠 목록 또는 상세가 노출될 때 발생
   *
   * @param properties The event's properties (e.g. article_id)
   * @param options Amplitude event options.
   */
  impressionSavedContent(
    properties?: ImpressionSavedContentProperties,
    options?: EventOptions,
  ) {
    return this.track(new ImpressionSavedContent(properties), options);
  }

  /**
   * Saved_Article
   *
   * [View in Tracking Plan](https://data.amplitude.com/pinback/default/events/main/latest/Saved_Article)
   *
   * 현재 페이지를 저장했을 때 발생
   *
   * @param properties The event's properties (e.g. article_id)
   * @param options Amplitude event options.
   */
  savedArticle(
    properties?: SavedArticleProperties,
    options?: EventOptions,
  ) {
    return this.track(new SavedArticle(properties), options);
  }

  /**
   * Saved_Shared_Bookmark
   *
   * [View in Tracking Plan](https://data.amplitude.com/pinback/default/events/main/latest/Saved_Shared_Bookmark)
   *
   * 공유 북마크를 내 목록에 저장했을 때 발생
   *
   * @param properties The event's properties (e.g. article_id)
   * @param options Amplitude event options.
   */
  savedSharedBookmark(
    properties?: SavedSharedBookmarkProperties,
    options?: EventOptions,
  ) {
    return this.track(new SavedSharedBookmark(properties), options);
  }

  /**
   * Triggered_Reminder
   *
   * [View in Tracking Plan](https://data.amplitude.com/pinback/default/events/main/latest/Triggered_Reminder)
   *
   * 리마인드 알림이 실제 발송되었을 때 발생
   *
   * @param properties The event's properties (e.g. article_id)
   * @param options Amplitude event options.
   */
  triggeredReminder(
    properties?: TriggeredReminderProperties,
    options?: EventOptions,
  ) {
    return this.track(new TriggeredReminder(properties), options);
  }
}

export const ampli = new Ampli();

// BASE TYPES
type BrowserOptions = amplitude.Types.BrowserOptions;

export type BrowserClient = amplitude.Types.BrowserClient;
export type BaseEvent = amplitude.Types.BaseEvent;
export type IdentifyEvent = amplitude.Types.IdentifyEvent;
export type GroupEvent = amplitude.Types.GroupIdentifyEvent;
export type Event = amplitude.Types.Event;
export type EventOptions = amplitude.Types.EventOptions;
export type Result = amplitude.Types.Result;
